import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

@testable import WhackAPivotSwift
class FakeLoginViewControllerDelegate : LoginViewControllerDelegate, Equatable {
    init() {
    }

    private(set) var loginSuccessfulCallCount : Int = 0
    func loginSuccessful() {
        self.loginSuccessfulCallCount += 1
    }

    static func reset() {
    }
}

func == (a: FakeLoginViewControllerDelegate, b: FakeLoginViewControllerDelegate) -> Bool {
    return a === b
}