import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

@testable import WhackAPivotSwift

class FakePeopleRandomizer : PeopleRandomizer {
    init() {
    }

    private(set) var getRandomSubsetCallCount : Int = 0
    var getRandomSubsetStub : (([Person], Set<Person>) -> (PeopleChoicesAndTarget
))?
    private var getRandomSubsetArgs : Array<([Person], Set<Person>)> = []
    func getRandomSubsetReturns(stubbedValues: (PeopleChoicesAndTarget
)) {
        self.getRandomSubsetStub = {(people: [Person], peopleToAvoid: Set<Person>) -> (PeopleChoicesAndTarget
) in
            return stubbedValues
        }
    }
    func getRandomSubsetArgsForCall(callIndex: Int) -> ([Person], Set<Person>) {
        return self.getRandomSubsetArgs[callIndex]
    }
    func getRandomSubset(people: [Person], peopleToAvoid: Set<Person>) -> (PeopleChoicesAndTarget
) {
        self.getRandomSubsetCallCount++
        self.getRandomSubsetArgs.append((people, peopleToAvoid))
        return self.getRandomSubsetStub!(people, peopleToAvoid)
    }

    static func reset() {
    }
}
