import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

@testable import WhackAPivotSwift

class FakePeopleChoicesAndTargetService : PeopleChoicesAndTargetService, Equatable {
    init() {
    }
    
    private(set) var provideCallCount : Int = 0
    var provideStub : (() -> (PeopleChoicesAndTarget))?
    func provideReturns(stubbedValues: (PeopleChoicesAndTarget)) {
        self.provideStub = {() -> (PeopleChoicesAndTarget) in
            return stubbedValues
        }
    }
    func provide() -> (PeopleChoicesAndTarget) {
        self.provideCallCount += 1
        return self.provideStub!()
    }
    
    static func reset() {
    }
}

func == (a: FakePeopleChoicesAndTargetService, b: FakePeopleChoicesAndTargetService) -> Bool {
    return a === b
}