import Foundation
import UIKit

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

@testable import WhackAPivotSwift

class FakePersonDisplayer: PersonDisplayer, Equatable {
    init() {
    }
    
    private(set) var displayCallCount : Int = 0
    private var displayArgs : Array<(Person, UIButton)> = []
    func displayArgsForCall(callIndex: Int) -> (Person, UIButton) {
        return self.displayArgs[callIndex]
    }
    func display(person: Person, button: UIButton) {
        self.displayCallCount += 1
        self.displayArgs.append((person, button))
    }
    
    static func reset() {
    }
}

func == (a: FakePersonDisplayer, b: FakePersonDisplayer) -> Bool {
    return a === b
}