import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

@testable import WhackAPivotSwift

class FakePeopleService : PeopleService {
    init() {
    }

    private(set) var getPeopleCallCount : Int = 0
    var getPeopleStub : (() -> ([Person]
))?
    func getPeopleReturns(stubbedValues: ([Person]
)) {
        self.getPeopleStub = {() -> ([Person]
) in
            return stubbedValues
        }
    }
    func getPeople() -> ([Person]
) {
        self.getPeopleCallCount++
        return self.getPeopleStub!()
    }

    static func reset() {
    }
}
